name: automerge
on: [pull_request]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@c9c919bb84b7b8d5eb924580665e0bf689ec060b"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
