name: "Comprueba hitos y milestones"
on:
  pull_request:
    paths:
      - 'proyectos/hito*.md'
      - '!proyectos/hito-1.md'

jobs:
  obtain-repo:
    runs-on: ubuntu-latest
    steps:
      - name: getDiff
        uses: JJ/github-pr-contains-action@releases/v1
        with:
          github-token: ${{github.token}}
          filesChanged: 1
      - name: obtain-repo
        uses: JJ/repo-in-diff-gh-action@releases/v0
        with:
          github-token: ${{github.token}}
          minMilestones: 3

